wireapp/wire-ios-message-strategy

- Source/Transcoders/FileUploadRequestStrategy.swift
- Source/Transcoders/ImageUploadRequestStrategy.swift
* The nullability of some parameters was changed in https://github.com/wireapp/wire-ios-data-model/pull/66, this PR updates the message strategy framework accordingly.
> Update for nullability changes in wire-ios-data-model

- Source/Transcoders/AssetDownloadRequestStrategy.swift
- Source/Transcoders/LinkPreviewAssetDownloadRequestStrategy.swift
- Tests/Source/AssetDownloadRequestStrategyTests.swift
* Add logic to `AssetDownloadRequestStrategy` to download an asset from the `v3` endpoint.
* We distinguish between v3 and v2 assets by inspecting the `ZMAssetRemoteData` in the genericMessage, if we have an assetId inside the protobuf we are dealing with a v3 asset and want to download it from the new endpoint.
* Added additional tests and ported existing tests to work with v3 assets as well.
> Add initial logic to download assets from the v3 endpoint

- Source/Transcoders/AssetDownloadRequestStrategy.swift
- Source/Transcoders/AssetV3PreviewDownloadStrategy.swift
- Source/Transcoders/ImageDownloadRequestStrategy.swift
- Tests/Source/AssetDownloadRequestStrategyTests.swift
- Tests/Source/AssetV3PreviewDownloadRequestStrategyTests.swift
- WireMessageStrategy.xcodeproj/project.pbxproj
This adds a new strategy which is only used to download preview images for files uploaded using the `/assets/v3` endpoint. The reason not to put this logic in the v3 file download strategy is as follows:
* There are multiple things we want for file downloads but not for the image preview, like progress etc.
* The AssetDownloadStrategy already has to deal with v2 and v3 assets, increasing this to preview images makes the code hard to reason about and unnecessarily bloats this class.
Update tests for a new data model with a asset client message version identifier.
> Add strategy to download asset /v3 file previews

- Source/Transcoders/AssetV3PreviewDownloadStrategy.swift
- Source/Transcoders/ImageDownloadRequestStrategy.swift
- Tests/Source/AssetV3PreviewDownloadRequestStrategyTests.swift
The `AssetV3PreviewDownloadRequestStrategy` used a wrong predicate only downloading the preview when the assets `transferState` was `.downloading`, instead we want to whitelist the image download when the UI calls `requestImageDownload`.
Thus this PR changes the implementation to use a `ZMDownstreamObjectSyncWithWhitelist` and listen to image download notifications as well as  adjusts the predicate for objects that need to be downloaded.
> Add whitelist to AssetV3PreviewDownloadRequestStrategy and fix predicate

- Source/Transcoders/AssetV3DownloadRequestStrategy.swift
- Tests/Source/AssetV3DownloadRequestStrategyTests.swift
* Instead of only using the asset ID as cache key / url we now use the version with the filename appended.
> Use correct cache key

- Source/Helpers/FilePreprocessor.swift
- Source/Transcoders/AssetV3FileUploadRequestStrategy.swift
- Source/Transcoders/FileUploadRequestStrategy.swift
- Tests/Source/FilePreprocessorTests.swift
We were starting the file preprocessing (full asset) as soon as the user inserts a file message (v3), when this operation completes an `Asset.Uploaded` with the otr key and the sha256 of the encrypted file is added to the data set of the message. This operation can happen very fast and lead to the `Asset.Uploaded` being uploaded together with the `Asset.Original`. This is not necessarily a bad thing, but we set the `uploadState` to `.uploaded` on the receiving side as soon as we receive a generic message containing an `Asset.Uploaded`. 
This PR fixes this issue and modifies the predicate for the file preprocessing to start when the `uploadingState` is set to `.uploadingFullAsset`. There is another possibility to check this on the receiving side and only change the state to `.uploaded` …
> Fix bug preprocessing the full asset before in the uploadingFullAsset state

- Source/Transcoders/ZMClientMessageTranscoder.m
**In this PR**
We are currently not creating notifications for images sent from iOS. The cause is the change from fetching an individual event when receiving an APNS to fetching the notification stream and the fact that we are still sending preview images for image messages.
_The previous behaviour:_ 
We receive a push event for the medium image
fetch the event
insert a message accordingly 
create a notification
_The new behaviour:_
We receive a push event for the medium image
fetch all missed event (which includes the preview image which does not create an APNS but is still sent on iOS)
insert a message for the preview event, 
update the message with the medium event 
Bug: do not create a notification because the causing push did NOT insert, but update a message
Fix: forward updated …
> forward updated messages to local notification dispatcher

- Source/Transcoders/AssetV3DownloadRequestStrategy.swift
- Tests/Source/AssetV3DownloadRequestStrategyTests.swift
[#7660](https://wearezeta.atlassian.net/browse/ZIOS-7660): Very rarely files uploaded using the `/assets/v3` endpoint have been unable to download on the receiving side. When checking the logs it is visible that the file is actually uploaded and downloaded successfully, so there either has to be a condition in which the data can be corrupted, the keys don't match or something else goes wrong when trying to decrypt the data. To find the root of this issue this PR adds more logging to the decryption step after downloading a v3 asset.
> Add asset v3 download logging

- Source/Transcoders/ImageUploadRequestStrategy.swift
**What's in this PR**
This PR adds an option to configure the amount of concurrent image processing operation.
This is needed for share extension (which sets it to a serial queue), as this would allocate too much memory, and the system would kill the extension.
> Add option to choose how many image to process in parallel 

- Source/Transcoders/AssetV3DownloadRequestStrategy.swift
- Tests/Source/AssetV3DownloadRequestStrategyTests.swift
**What's in this PR**
We force recompute the category of a Assetv3 client message after downloading it's content.
> Fix that force update the file category after downloading content on assetv3

- Source/Helpers/ZMOTRMessage+Missing.swift
- Source/Transcoders/MissingClientsRequestStrategy.swift
* The share extension did not fetch missing clients when receiving a 412 when sending a message, this was due to the `MissingClientsRequestStrategy` not correctly being included in the set of potential request generators.
* The `MissingClientsRequestStrategy` implements the `nextRequest` method and is thus conforming to the `RequestStrategy` protocol, but was not declared as doing so.
* The conformance is needed in `wire-ios-share-engine` when we construct the set of request generators, where we check for conformance to `RequestStrategy` or `ZMRequestGeneratorSource`.
> Conform MissingClientsRequestStrategy to RequestStrategy protocol

- WireMessageStrategy.xcodeproj/project.pbxproj
* Set `APPLICATION_EXTENSION_API_ONLY ` in order to remove warnings in other frameworks.
> Set application extension only API flag to YES

- Source/Transcoders/AssetClientMessageRequestStrategy.swift
- Tests/Source/AssetClientMessageRequestStrategyTests.swift
* We failed to set the `uploadState` after successful uploading a v3 file message representing an image.
> Fix image message uploaded state not being set to `.done` after successful upload

- Source/Transcoders/ClientMessageTranscoder.swift
- Tests/Source/AssetV3DownloadRequestStrategyTests.swift
- Tests/Source/AssetV3ImageUploadRequestStrategyTests.swift
- Tests/Source/ClientMessageTranscoderTests+Ephemeral.swift
- Tests/Source/GenericMessageRequestStrategyTests.swift
- Tests/Source/Helpers/MessagingTestBase.swift
- Tests/Source/LinkPreviewPreprocessorTests.swift
- Tests/Source/MissingClientsMapTests.swift
If your tests are crashing during a save with the error: "Failed to save: Error Domain=NSCocoaErrorDomain Code=133010" - it's probably because your tests are manipulating sync objects on the main thread. All you need to do is wrap your tests in a syncMoc.performGroupedBlock{} and you are fine. Voilá
> Fix failing tests

- Source/Transcoders/ClientMessageTranscoder.swift
* `ClientMessageTranscoder` is a strategy now but was not marked as conforming to the `RequestStrategy` protocol.
* This was breaking text message sending from the share extension as `wire-ios-share-engine` doesn't ask `ZMRequestGenerator`s for their `nextRequest` but instead `ZMRequestGeneratorSource`s (which `ClientMessageTranscoder` isn't anymore).
> Mark `ClientMessageTranscoder` as `RequestStrategy`

- Source/Transcoders/FetchingClientRequestStrategy.swift
- Tests/Source/FetchingClientRequestStrategyTests.swift
Clients that don't have a database entry but a session are not treated as "new".
> Treat all non-existing clients as new clients

- Source/Helpers/EncryptionSessionDirectory+UpdateEvents.swift
When failing to decrypt a message, we were not showing degradation message
> Make sure we display a degradation warning when receiving a message

- Source/Helpers/FilePreprocessor.swift
- Source/Transcoders/AssetV3FileUploadRequestStrategy.swift
- Tests/Source/AssetV3FileUploadRequestStrategyTests.swift
**TL;DR: This PR fixes an issue resulting in files being sent that are unable to decrypt / have an sha256 which doesn't match.**
* In very rare cases it happened that file messages (sent using the `/assets/v3` endpoint) could not be decrypted on the receiving side, this only happened for file messages and not images (which are also files and sent using the same endpoint, but by a different `RequestStrategy`). The odd thing to note here is was 100% reproducibly which specific files on specific devices, the `sha256` did not match the file data. The underlying bug was, that the `FilePreprocessor`, which encrypts the file, updates the generic message with the `otrKey` and `sha256` had a wrong predicate. The predicate did not check if there already were encryption keys in the generic message …
> Fix multiple preprocessing runs resulting in race condition

- Tests/Source/AssetDownloadRequestStrategyTests.swift
- Tests/Source/FileUploadRequestStrategyTests.swift
* Remove observers created using the `NotificationCenter` blocks API.
> Remove block observers in tests

- Source/Transcoders/TeamDownloadRequestStrategy+Events.swift
- Tests/Source/TeamDownloadRequestStrategy+EventsTests.swift
* The `team.member-join` event payload does not include the permissions of the added member.
To be sure we no mark the members as needing to be refetched to ensure we always have all member permissions locally (see https://github.com/wireapp/architecture/issues/13).
* We now delete a local team in case we receive a `team.member-leave` update event for the self user.
> Refetch all team members after processing a team.member-join event

- Source/Transcoders/TeamDownloadRequestStrategy+Events.swift
- Tests/Source/TeamDownloadRequestStrategy+EventsTests.swift
* When receiving a `team/member-leave` update event for an user other than self, we will not receive any `conversation.member-leave` events. We now remove the removed member from all team conversations manually.
* Fixes https://github.com/wearezeta/backend-issues/issues/573 client-side.
* Currently there is one culprit, which is that there will be no `XYZ left` system message inserted in said conversations. This needs to be done in `wire-ios-data-model` when creating system message from update events (cf. `createOrUpdateMessageFromUpdateEvent` in `ZMMessage.m:854`).
> Remove user from team conversations member leave

- Source/Transcoders/TeamDownloadRequestStrategy+Events.swift
- Tests/Source/TeamDownloadRequestStrategy+EventsTests.swift
* Always refetch a team in case the self user just joined.
> Refetch team in case the selfUser joined

- Source/Helpers/ApplicationStatus.swift
- Source/Transcoders/AbstractRequestStrategy.swift
- Source/Transcoders/AssetClientMessageRequestStrategy.swift
- Source/Transcoders/AssetV3DownloadRequestStrategy.swift
- Source/Transcoders/AssetV3FileUploadRequestStrategy.swift
- Source/Transcoders/ClientMessageTranscoder.swift
- Source/Transcoders/FetchingClientRequestStrategy.swift
- Source/Transcoders/LinkPreviewAssetUploadRequestStrategy.swift
- Source/Transcoders/LinkPreviewUploadRequestStrategy.swift
- Source/Transcoders/MissingClientsRequestStrategy.swift
- Source/ZMStrategyConfigurationOption.h
- Tests/Source/ClientMessageTrancoderTests+MessageConfirmation.swift
- Tests/Source/Helpers/MockObjects.swift
- Tests/Source/LinkPreviewUploadRequestStrategyTests.swift
* We now query if we are currently fetching the notification stream as response to receiving a push notification before creating requests in the client message transcoder.
* Fix `LinkPreviewUploadRequestStrategy` generating events during sync.
> Add notification fetch status to app.-status and don't create request while in progress

- Source/Helpers/EncryptionSessionDirectory+UpdateEvents.swift
- Tests/Source/CryptoBoxUpdateEventsTests.swift
* Limit receiving payload size to 18.000 characters (see the  [corresponding wire-webapp PR](https://github.com/wireapp/wire-webapp/pull/1410/)).
* In case the encrypted, base64 encoded payload is too large we insert a `"Unable to decrypt"` message, as does the web.
> Limit receiving payload size

- Source/Transcoders/ClientMessageTranscoder.swift
We want to pass all message notifications to the local notification dispatcher in order to generate custom in app chat heads.
> don’t filter out message events from web socket

- Source/Helpers/AssetAnalytics.swift
Related to https://github.com/wireapp/wire-ios-share-engine/pull/47 and https://github.com/wireapp/wire-ios-sync-engine/pull/574
> added guard to the missing userInterface object in order to avoid Share Extension to crash
